"strict mode"

const quotes = [
  "Life is what happens when you're busy making other plans.",
  "The purpose of our lives is to be happy.",
  "Life is short, and it's up to you to make it sweet.",
  "Life is really simple, but we insist on making it complicated.",
  "The biggest adventure you can take is to live the life of your dreams.",
  "Life is not about waiting for the storm to pass but about learning how to dance in the rain.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "The purpose of life is a life of purpose.",
  "Believe you can and you're halfway there.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "You are never too old to set another goal or to dream a new dream.",
  "It does not matter how slowly you go as long as you do not stop.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The best way to predict the future is to create it.",
  "Start where you are. Use what you have. Do what you can.",
  "Don't watch the clock; do what it does. Keep going.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "The only way to do great work is to love what you do.",
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice, and most of all, love of what you are doing or learning to do.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "The harder you work for something, the greater you'll feel when you achieve it.", "Opportunities are usually disguised as hard work, so most people don't recognize them.",
  "Hard work beats talent when talent doesn't work hard.",
  "Success is the result of preparation, hard work, and learning from failure.",
  "I'm a great believer in luck, and I find the harder I work, the more I have of it.", "The only place where success comes before work is in the dictionary.",
  "Dreams don’t work unless you do.",
  "I learned the value of hard work by working hard.",
  "Patience is not simply the ability to wait—it's how we behave while we're waiting.", "Patience is the companion of wisdom.",
  "Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.",
  "The two most powerful warriors are patience and time.", "Have patience. All things are difficult before they become easy.",
  "Patience is bitter, but its fruit is sweet.",
  "To lose patience is to lose the battle.",
  "Adopt the pace of nature: her secret is patience.",
  "One moment of patience may ward off great disaster. One moment of impatience may ruin a whole life.",
  "Rivers know this: there is no hurry. We shall get there some day.",
  "Do not take life too seriously. You will never get out of it alive.",
  "Life is either a daring adventure or nothing at all.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "Life is a series of natural and spontaneous changes. Don’t resist them—that only creates sorrow. Let reality be reality.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "The good life is one inspired by love and guided by knowledge.",
  "Life isn’t about finding yourself. Life is about creating yourself.",
  "The longer I live, the more I realize the impact of attitude on life.",
  "Life is about making an impact, not making an income.",
  "Life is too important to be taken seriously.",
  "You don't have to be great to start, but you have to start to be great.",
  "Don't let what you cannot do interfere with what you can do.",
  "It always seems impossible until it's done.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Act as if what you do makes a difference. It does.",
  "You are never too small to make a difference.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "It doesn't matter how many times you get knocked down, but how many times you get up.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "Do not whine... Do not complain. Work harder. Spend more time alone.",
  "Things may come to those who wait, but only the things left by those who hustle.", "There are no shortcuts to any place worth going.",
  "If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all.",
  "I’m a greater believer in luck, and I find the harder I work the more I have of it.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The road to success and the road to failure are almost exactly the same.",
  "I find that the harder I work, the more luck I seem to have.",
  "Without labour, nothing prospers.",
  "Patience, persistence, and perspiration make an unbeatable combination for success.",
  "Patience is the art of hoping.",
  "The key to everything is patience. You get the chicken by hatching the egg, not by smashing it.",
  "Patience is necessary, and one cannot reap immediately where one has sown.", "Endurance is patience concentrated.",
  "Be patient and tough; someday this pain will be useful to you.",
  "Patience is the best remedy for every trouble.",
  "To endure is the first thing that a child ought to learn, and that which he will have most need to know.",
  "Patience and diligence, like faith, remove mountains.",
  "With love and patience, nothing is impossible.", "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "Life is not about finding yourself. Life is about creating yourself.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Life is ten percent what happens to us and ninety percent how we respond to it.", "Do not let making a living prevent you from making a life.",
  "Life isn't about waiting for the storm to pass, it's about learning how to dance in the rain.",
  "Life is what we make it, always has been, always will be.",
  "The only impossible journey is the one you never begin.",
  "Good friends, good books, and a sleepy conscience: this is the ideal life.",
  "Life is really simple, but we insist on making it complicated.",
  "You miss 100% of the shots you don't take.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "If you can dream it, you can do it.",
  "It always seems impossible until it's done.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Your life does not get better by chance, it gets better by change.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "When you have a dream, you've got to grab it and never let go.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't watch the clock; do what it does. Keep going.",
  "The harder you work, the luckier you get.",
  "There is no substitute for hard work.",
  "Great things come from hard work and perseverance. No excuses.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Striving for success without hard work is like trying to harvest where you haven't planted.",
  "Nothing worth having comes easy.",
  "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.",
  "The harder you work for something, the greater you'll feel when you achieve it.", "If you work hard enough and assert yourself, and use your mind and imagination, you can shape the world to your desires.",
  "Perseverance is the hard work you do after you get tired of doing the hard work you already did.",
  "Dream big. Work hard. Stay focused & surround yourself with good people.",
  "Patience is the key to paradise.",
  "Patience is a conquering virtue.",
  "Patience is not simply the ability to wait - it's how we behave while we're waiting.",
  "Patience is power. Patience is not an absence of action; rather it is 'timing'; it waits on the right time to act, for the right principles and in the right way.",
  "All things are difficult before they are easy.",
  "The strongest of all warriors are these two — Time and Patience.",
  "He that can have patience can have what he will.",
  "Patience is the calm acceptance that things can happen in a different order than the one you have in mind.",
  "To lose patience is to lose the battle.",
  "Patience and diligence, like faith, remove mountains.",
  "One moment of patience may ward off great disaster. One moment of impatience may ruin a whole life.",
  "Patience is the best remedy for every trouble.",
  "Patience is a key element of success.",
  "Have patience. All things are difficult before they become easy.",
  "Rivers know this: there is no hurry. We shall get there some day.",
  "Endurance is patience concentrated.",
  "With love and patience, nothing is impossible.",
  "The more you know yourself, the more patience you have for what you see in others.", "Life is not about waiting for the storm to pass but about learning how to dance in the rain.",
  "Life is a series of natural and spontaneous changes. Don't resist them - that only creates sorrow. Let reality be reality.",
  "The purpose of life is a life of purpose.",
  "Life is a journey that must be travelled no matter how bad the roads and accommodations.",
  "Life is short, and it's up to you to make it sweet.",
  "Life is what we make it, always has been, always will be.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "Life is really simple, but we insist on making it complicated.", "Do not take life too seriously. You will never get out of it alive.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "You are never too old to set another goal or to dream a new dream.",
  "Believe you can and you're halfway there.", "The only way to do great work is to love what you do.",
  "It does not matter how slowly you go as long as you do not stop.",
  "You miss 100% of the shots you don't take.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.", "The best way to predict the future is to create it.",
  "Your life does not get better by chance, it gets better by change.",
  "Don't watch the clock; do what it does. Keep going.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "When you have a dream, you've got to grab it and never let go.",
  "Great things come from hard work and perseverance. No excuses.",
  "Dream big. Work hard. Stay focused & surround yourself with good people."
]


const usedIndexes = new Set()
const quoteElement = document.getElementById("quote");


function generateQuotes() {

  if (usedIndexes.size >= quotes.length) {
    usedIndexes.clear()

  }

  while (true) {
    const randomIdx = Math.floor(Math.random() * quotes.length)

    if (usedIndexes.has(randomIdx)) continue

    const quote = quotes[randomIdx]
    quoteElement.innerHTML = quote;
    usedIndexes.add(randomIdx);
    break
  }

  // quoteElement.innerHTML = 'Ramadhan'
}

